//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyConverterExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrencyConverterExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion API Key.
        /// </summary>
        internal static string api_key {
            get {
                return ResourceManager.GetString("api_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) Provide the API key for the service if necessary.
        /// </summary>
        internal static string api_key_description {
            get {
                return ResourceManager.GetString("api_key_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Cache duration.
        /// </summary>
        internal static string cache_duration {
            get {
                return ResourceManager.GetString("cache_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration should be mentioned in hours. Min: 0.5, Max: 24.
        /// </summary>
        internal static string cache_duration_description {
            get {
                return ResourceManager.GetString("cache_duration_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion API.
        /// </summary>
        internal static string conversion_api {
            get {
                return ResourceManager.GetString("conversion_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;Default&apos; if you are not sure which one to use. Be sure to read the plugin&apos;s readme file on GitHub if you plan to change this option to avoid any side effects..
        /// </summary>
        internal static string conversion_api_description {
            get {
                return ResourceManager.GetString("conversion_api_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Conversion Currencies.
        /// </summary>
        internal static string currencies {
            get {
                return ResourceManager.GetString("currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add currencies comma separated. eg: USD, EUR, BTC.
        /// </summary>
        internal static string currencies_description {
            get {
                return ResourceManager.GetString("currencies_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyAPI.
        /// </summary>
        internal static string currency_api {
            get {
                return ResourceManager.GetString("currency_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal format separator.
        /// </summary>
        internal static string decimal_separator {
            get {
                return ResourceManager.GetString("decimal_separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change between dots and commas for decimal separation.
        /// </summary>
        internal static string decimal_separator_description {
            get {
                return ResourceManager.GetString("decimal_separator_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default API.
        /// </summary>
        internal static string default_api {
            get {
                return ResourceManager.GetString("default_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExchangeRateAPI.
        /// </summary>
        internal static string exchange_rate_api {
            get {
                return ResourceManager.GetString("exchange_rate_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frankfurter.
        /// </summary>
        internal static string frankfurter_api {
            get {
                return ResourceManager.GetString("frankfurter_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Conversion Local Currency.
        /// </summary>
        internal static string local_currency {
            get {
                return ResourceManager.GetString("local_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your local currency for quick conversion.
        /// </summary>
        internal static string local_currency_description {
            get {
                return ResourceManager.GetString("local_currency_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twelve Data.
        /// </summary>
        internal static string twelve_data_api {
            get {
                return ResourceManager.GetString("twelve_data_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress fallback warnings.
        /// </summary>
        internal static string suppress_fallback_warnings {
            get {
                return ResourceManager.GetString("suppress_fallback_warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a home-list conversion fails, show Convert "query" with Currency Converter instead of an error. Only applies to queries that look like a conversion.
        /// </summary>
        internal static string suppress_fallback_warnings_description {
            get {
                return ResourceManager.GetString("suppress_fallback_warnings_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always use commas for decimals.
        /// </summary>
        internal static string use_commas {
            get {
                return ResourceManager.GetString("use_commas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always use dots for decimals.
        /// </summary>
        internal static string use_dots {
            get {
                return ResourceManager.GetString("use_dots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system default.
        /// </summary>
        internal static string use_system_default {
            get {
                return ResourceManager.GetString("use_system_default", resourceCulture);
            }
        }
    }
}
